### ISSUE TITLE
Host token spoofing kick reaction set to stranger kicks friends

### ISSUE THREAD

**Issue by Iamsoop** [calamity-inc/Stand-Feedback#128] opened 2024-06-29 19:39 UTC
I have set as a reaction to some spoofing their host token that they get love letter kicked, problem here is that even i set it to strangers, my friends also get kicked whilst joining a new lobby.

**Comment by Sainan** [comment] 2024-08-06 05:40
Duplicate of #32

**Closed as not planned by Sainan** 2024-08-06 05:40 UTC
Labels: bug
