### ISSUE TITLE
Children not set as temporary

### ISSUE THREAD

**Issue by NotLegish** [calamity-inc/Stand-Feedback#39] opened 2024-06-10 21:29 UTC
When you set a list as temporary, it's children are not set as temporary. I believe if the top command is temporary it's children must be temporary as well?

```lua
local container = menu.my_root():list("list", {}, "")
container:setTemporary()

container:toggle("Child Command", {}, "", function() end)
container:toggle("Child Command", {}, "", function() end):setTemporary()

container:setTemporary()
```

**Comment by Sainan** [comment] 2024-06-10 22:50
Works as intended. Each command has its own flags, and typically the tree is not walked upwards to inherit/discover flags like 'temporary', but semantically, you should give every child of a temporary list the temporary flag as well. Of course, the question is why this even matters to you, because typically you should really try to get your commands created at tick 1 and work with Stand's state system. And player commands are already marked as temporary for you by Stand.

**Closed as not planned by Sainan** 2024-06-10 22:50 UTC
Labels: bug
