### ISSUE TITLE
Fixing Asset Hashes Patched

### ISSUE THREAD

**Issue by heee-mk** [calamity-inc/Stand-Feedback#432] opened 2024-12-22 02:15 UTC
I am unable to play gta online with other people while I am using modded game files and "fix asset hashes" is enabled for me. When I host a session, nobody joins my lobby (using player magnet). This is not an issue with vanilla game files. When I join a public lobby I am instantly desynced and made the host (it's not a battleye kick because it happens instantly, while battleye kick takes a few minutes). So I am isolated while using modified game files and "fix asset hashes". None of my mods are causing this issue since before the Christmas update, all my mods were working fine.  It's not due to outdated mods either, since I updated all my mods. Whenever I modify game files which GTA Online uses that causes the issue. The other mods I am using are reShade with (GTAVUpscaler.asi and NVE.asi as plugins), FSL, ScriptHookV and NVE.Reflections.asi They are all up to date and cause no issues in Online.

**Comment by Sainan** [comment] 2024-12-24 21:48
Duplicate of #431

**Closed as not planned by Sainan** 2024-12-24 21:48 UTC
Labels: bug
