### ISSUE TITLE
Multiplex Session/ Player Magnet to session

### ISSUE THREAD

**Issue by joaopgomes** [calamity-inc/Stand-Feedback#255] opened 2024-07-28 18:14 UTC
I thought that it would be a great idea and a great feature to have something that creates multiple instances of our session and makes player more likely to join our session when going to online. So you could fill your session if you decide too.
I saw someone that had a menu that could do that and it worked great.

**Comment by Sainan** [comment] 2024-07-28 18:57
Duplicate of #132

**Closed as not planned by Sainan** 2024-07-28 18:57 UTC
Labels: feature request
