### ISSUE TITLE
Steamroll Crashing 1 Person causes most of the lobby to leave

### ISSUE THREAD

**Issue by heee-mk** [calamity-inc/Stand-Feedback#406] opened 2024-11-02 07:37 UTC
When I steam roll crash 1 person most of the lobby (which is full) leaves the game leaving only 1-5 other people. I don't know if it's from them being kicked or if they were crashed too. All the times this happened I was host. I haven't tried it when I wasn't host

**Comment by isytrana** [comment] 2024-12-05 17:34
It's written that Steamroller MAY crash players nearby the target, most likely not a bug.

**Comment by Sainan** [comment] 2024-12-10 17:22
Thanks for the report, will be fixed in the next update.

**Closed as completed by Sainan** 2024-12-10 17:22 UTC
Labels: bug
