### ISSUE TITLE
Indestructible Is bugged with Progen PR4 open wheel car

### ISSUE THREAD

**Issue by TechnoMonkeyDJ** [calamity-inc/Stand-Feedback#345] opened 2024-09-07 08:02 UTC
A good issue report has _at least one_ of these:
- ** It causes the car to get reset at 289 KM/H.**
  - For example: "Indestructible causes the Progen PR4 completely freak out bugged out and it tries to drive up the wall if you hit any"
- ** Just enabling the option for vehicle Indestructible and driving the Progen PR4 over 288 KM/H and the car will come to a complete halt**

**Comment by Sainan** [comment] 2024-09-07 12:47
I am not quite sure what you're saying, but I've ran some tests:
- PR4 with performance tuning doesn't reach more than ~180 KMH just driving legit.
- PR4 with performance tuning doesn't reach more than ~230 KMH when using Rocket Boost.
- If I use super drive, I can reach ~540 KMH (speed limit) no problem.
- The vehicle seems to be behaving as expected when ramming into walls.

**Comment by TechnoMonkeyDJ** [comment] 2024-09-07 13:15
I figured out some more details so. I spawn the new one, It's with the Side skirts 2/3/4/5/6.
It's fine with Side skirts -1/0/1. So some reason the other ones have the problem with the Indestructible enabled.
I was spawning my saved one with the side skirts 6.
I always play with speed limit and engine boost maxed so it feels more like Forza.
It's the only reason why I found the bug.

**Comment by Sainan** [comment] 2024-09-07 13:34
Thanks for the information. I managed to reproduce the issue. It will be fixed in the next update.

**Closed as completed by Sainan** 2024-09-07 13:34 UTC
Labels: bug
